kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bc-pvc-postgres
  namespace: bc-nmp-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
