apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bc-nmp-tools
  labels:
    app: nexus
  name: bc-dpm-nexus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nexus
    spec:
      containers:
        - image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          name: nexus3
          ports:
            - containerPort: 5000
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 2500Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - mountPath: /nexus-data
              name: bc-vlm-nexus
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: bc-vlm-nexus
          persistentVolumeClaim:
            claimName: bc-pvc-nexus
      securityContext:
        runAsUser: 0
        fsGroup: 200
