apiVersion: v1
kind: PersistentVolume
metadata:
  name: bc-pv-nexus
  namespace: bc-nmp-tools
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/nexus-data"
