apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-pvc-nexus
  namespace: bc-nmp-tools
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
