apiVersion: v1
kind: List
metadata:
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: nexus
      name: bc-srv-nexus
      namespace: bc-nmp-tools
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8081
      selector:
        app: nexus

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: nexus
      name: bc-srv-docker
      namespace: bc-nmp-tools
    spec:
      ports:
        - name: docker
          port: 5000
          protocol: TCP
          targetPort: 5000
      selector:
        app: nexus
