filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    output.logstash:
      hosts: '${LOGSTASH_URL}'

extraEnvs:
  - name: LOGSTASH_URL
    value: logstash-logstash-headless.elastic:5044